package bf22.intermediary;

public final class C0711 {
   public static final String[] tP = new String[]{
      "Bem vind@ ao",
      "Jogador expulso: ",
      ":que negócio é esse?",
      "Contundido: ",
      "O bicho vai pegar!",
      "Não aceitamos goleadas!",
      "Desse jeito você vai cair",
      " vai para o ",
      "Racha no elenco causado por ",
      "Agradecimento",
      "Reclamação do jogador ",
      "Estou sem contrato",
      "Briga entre ",
      "Torcida briga com ",
      " vendido ao ",
      "Convites para seleção",
      "Contrato se encerrando: ",
      "Contrato encerrado: ",
      " não pode voltar.",
      "Vitória no clássico",
      "Desempenho contra rival",
      "Grande vitória no clássico",
      "Derrota no clássico",
      "Pré-Classificados Copa BR",
      "Parabéns pelo título",
      "Parabéns pela grande conquista",
      "Premiação recebida",
      "Parabéns pela goleada!",
      "Empréstimo encerrado, time sem vagas",
      "Empréstimo encerrado",
      "Vaga na Liga Europa",
      "Vaga nas Oitavas da Liga Europa",
      "Vaga na Sul-Americana",
      "Vaga nas Oitavas da Sul-Americana",
      "Desejo de aposentadoria",
      "Vaga na Conference League",
      "Avalia\u00e7\u00e3o mensal da diretoria",
      "Contrato de patroc\u00ednio",
      "B\u00f4nus de patroc\u00ednio"
   };
   public static final String[] tQ = new String[]{
      "O jogador simplesmente cuspiu na cara do árbitro. 10 jogos de suspensão até que foi uma pena leve.",
      "Ele foi punido com 10 jogos por ofensas morais ao árbitro. Essa pena foi bem pesada.",
      "O STJD puniu o jogador por um carrinho desleal por trás, 5 jogos foi uma pena dura demais.",
      "O jogador pegou uma suspensão de 5 jogos por ter agredido intencionalmente o adversário.",
      "O jogador deu uma cotovelada no adversário. Nós da diretoria achamos que 5 jogos foi uma pena execessiva.",
      "O jogador foi punido por ter dado um carrinho desleal por trás, pegou 3 jogos de suspensão.",
      "O jogador pegou uma suspensão de 3 jogos por ter dado uma cotovelada no adversário.",
      "O jogador parou violentamente uma jogada de gol do adversário, pegou 3 jogos de suspensão. Nós achamos que ele não merecia estes 3 jogos! Estão de marcação com nosso time.",
      "O jogador deu um tapa na cara do adversário, 3 jogos até que foi uma pena leve.",
      "Pegou 3 jogos ao dividir violentamente a bola com o goleiro, que quase quebra a perna. Um pouco exagerada a suspensão.",
      "Fez uma falta dura no adversário, o juiz deu uma exagerada na súmula, por isso deram 2 jogos de suspensão.",
      "O jogador deu uma tesoura no adversário, será que ele pensa que futebol é luta-livre?",
      "Depois de um bate boca com o árbitro, ele foi expulso e o tribunal deu 2 jogos de suspensão.",
      "Recebeu dois jogos de suspensão por conduta antidesportiva.",
      "Um expulsão boba, era pra ser suspenso apenas por um jogo, mas o jogador foi inventar de xingar a mãe do árbitro...",
      "O jogador deu uma cotovelada no goleiro numa disputa de bola, deu sorte que o tribunal só deu 2 jogos de suspensão.",
      "Você acha que é quem cara? Eu nem tive culpa e você vem multando do meu salário? Assim fica complicado jogar neste time!",
      "Não gostei de você ter me multado. Se continuar assim o clima neste time vai ficar ruim.",
      "Não pode ficar me multando. Por acaso quando o time perde a diretoria te multa? A culpa foi do tribunal por ter me dados vários jogos de suspensão.",
      "A culpa pela suspensão não foi minha. Não merecia esta multa.",
      "A imprensa acaba de divulgar mais esta sensacional contratação que acaba de ocorrer nesta semana.",
      "A imprensa acaba de divulgar mais esta sensacional contratação que acaba de ocorrer nesta semana.",
      "O jogador foi apresentado hoje ao novo clube, é mais um reforço importante para a disputa do campeonato.",
      "Foi apenas uma pancada, mas que deixou uma leve lesão na coxa. Cerca de 2 semanas fora.",
      "Uma leve torção no tornozelo, em 2 semanas o jogador já terá condição.",
      "Sofreu uma pequena lesão muscular, talvez o esforço sobre o jogador venha sendo excessivo. Em 2 semanas estará bem.",
      "Entorce no tornozelo. Cerca de 3 semanas fora.",
      "Lesão muscular. Os jogadores estão sendo muito forçados. 3 semanas fora.",
      "Lesão muscular. Este jogador acabou forçando muito em uma jogada. Ficará 4 semanas de molho.",
      "Problema no musculo adutor na coxa. 4 semanas de recuperação.",
      "O jogador sofreu uma distensão muscular. Ficará mais de 5 semanas de recuperação.",
      "Sofreu uma grave torção no tornozelo. O departamento médico cuidara dele por algumas semanas.",
      "Em uma dividida o jogador acabou fraturando um dedo do pé, em algumas semana estará recuperado para jogo.",
      "O jogador sofreu uma pequena entorce no joelho, mas por precaução ficará algumas semanas fora de jogo. ",
      "O jogador sofreu uma distensão muscular. Procure não sobrecarregar os jogadores, tente poupar os que estão com menos energia.",
      "Uma torção no joelho colocará este jogador de molho por um bom tempo. 7 semanas é a previsão de volta.",
      "Lesão muscular. Talvez já seja hora de aposentar esse jogador, pois está se contundindo com mais facilidade e gravidade que os mais novos.",
      "Distensão muscular. Várias semanas fora.",
      "Grave contusão no músculo da virilha. Este jogador está com muito desgaste muscular.",
      "Lesão grave na panturrilha. Ficará por volta de dois meses fora.",
      "O jogador sofreu uma fratura na perna. Ficará um bom tempo sem jogar.",
      "Grave lesão no joelho. O jogador ficará muitas semanas parado.",
      "Este jogador ficará várias semanas sem jogar, fraturou o tornozelo.",
      "Lesão no tendão do calcanhar. Previsão é de um longo tempo parado.",
      "Seja bem vind@ ao nosso clube. Estamos em busca de uma grande campanha, não aceitaremos uma má gestão financeira. Boa sorte!",
      "Bem vind@ ao nosso clube. Aqui você receberá informações sobre os seus jogadores, comunicados etc. Não deixe de ler o manual.doc, que está na pasta principal onde o jogo foi instalado. Nele você encontrará estratégias financeiras, táticas etc.Também não deixe de visitar o fórum oficial no site do jogo,onde você poderá trocar idéias com outros jogadores, saber as últimas novidades e muito mais!",
      "Você está deixando que humilhem nosso clube. Nós da torcida não aceitaremos mais goleadas para nosso rival como esta!",
      "Agora você deixar golearem nosso time assim? Se continuar vamos pressionar a diretoria pedindo sua demissão.",
      "Nosso time não pode levar goleadas assim. Se continuar vamos protestar e pedir sua saída do time.",
      "O jogador foi mal recebido por parte dos outros jogadores, parece que há um racha no elenco. Talvez o problema seja o excesso de estrelas no time.",
      "A recente contratação causou uma divisão no elenco. Era de se esperar que isso ocorre-se pelo grande número de estrelas juntos.",
      "Eu não venho jogando há muito tempo no time, isto está me deixando infeliz. Gostaria de ser negociado ou começar a participar dos jogos do time.",
      "Eu não venho sendo aproveitado no time, não quero continuar a esquentar o banco. Gostaria de ser escalado nas próximas partidas.",
      "Estou sem contrato há vários jogos, esta situação me deixa inseguro no clube. Gostaria que meu contrato fosse renovado como uma nova oferta salarial ou que eu fosse negociado.",
      "Gostaria que meu contrato fosse renovado com um novo salário, pois esta situação indefinida me deixa inseguro para continuar no clube. ",
      "Uma briga durante os treinamentos entre estes dois jogadores tumultuou o elenco. Esperamos que daqui pra frente as coisas acalmem.",
      "Os dois jogadores partiram para a briga depois de uma dividida no treino. A diretoria exige que as coisas se acalmem no clube.",
      "A fase do time não anda nada bem, e os torcedores resolveram tumultuar o centro de treinamento do time, o resultado é que o jogador acabou brigando fisicamente com membros da torcida organizada.",
      "Na chega do time ao centro de treinamento o jogador foi hostilizado pela torcida e acabou sendo agredido.",
      "Os torcedores receberam os jogadores com violência na entrada do CT hoje.",
      "Estou sendo submetido à um esforço excessivo. Esta situação está me deixando descontente com a sua comissão técnica. Gostaria de ser poupado por 1 ou mais jogos.",
      "Eu não sou burro de carga! Você está me escalando sem eu ter condições físicas ideais, este excesso de jogos está me deixando descontente. Gostaria de ser poupado por 1 ou mais jogos.",
      "Fico muito contente com este bom aumento concedido por esta competente diretoria. Mostrarei em campo toda minha gratidão!",
      "Fico muito contente com este bom aumento concedido por esta competente diretoria. Mostrarei em campo toda minha gratidão!",
      "O jogador que estava à venda foi vendido por ",
      "Há rumores que você será convidado para dirigir alguma seleção que disputará a copa em breve, nos da diretoria já estamos recebendo algumas informações. Em breve você deverá receber os convites.",
      "O jogador termina seu contrato em menos de 1 mês.",
      "O jogador teve seu contrato encerrado.",
      "O jogador teve seu contrato de empréstimo encerrado. Mas como você tem o limite de 30 jogadores ele só poderá voltar quando tiver um lugar no elenco.",
      "Parabéns pela vitória no classíco! Vencer campeonatos é importante, vencer clássicos mais ainda!",
      "Parabéns pela vitória no classíco! Ganhar do rival tem sempre um gostinho especial!",
      "Derrotar nosso rival é sempre uma meta a ser alcançada, parabéns!",
      "Ganhar um campeonato é ótimo, mas derrotar nosso rival no clássico é melhor ainda!",
      "Aqui você receberá mensagens sobre a situação de seus jogadores, premiações recebidas e outras informações. A diretoria lhe deseja boa sorte e esperamos muitas vitórias!",
      "Boa sorte neste novo emprego. Temos uma torcida exigente e nosso clube espera muitas vitórias!",
      "11 times estão pré-classificados para as oitavas da Copa do Brasil. Lembrando que na primeira fase o empate classifica o visitante. Confira a lista:",
      "Parabéns pelo título! Essa conquista $1 nos dá ainda mais confiança em seu trabalho!",
      "Parabéns pelo título! A torcida ficou muito satisfeita com mais essa conquista!",
      "Excelente trabalho! Ganhar o mundial é um sonho para qualquer time. Parabéns!",
      "Você recebeu uma premiação de $1 pela vitória ($2).",
      "Você recebeu uma premiação de $1 pela classficação final ($2).",
      "Golear nosso rival em um clássico é sempre uma festa pra torcida! Parabéns!",
      "A data de empréstimo do jogador $1 terminou. Mas será prorrogado até o time de origem tiver uma vaga para recebê-lo.",
      "O jogador $1 retornou do empréstimo.",
      "O empréstimo do jogador $1 terminou e ele voltou ao clube de origem.",
      "Seu time foi eliminado da Liga dos Campeões, mas garantiu uma vaga em uma das fases da Liga Europa",
      "Seu time ficou em terceiro lugar no grupo da Liga dos Campeões e foi eliminado, mas garantiu uma vaga nas oitavas de final da Liga Europa.",
      "Seu time foi eliminado da Libertadores, mas garantiu uma vaga na fase de grupos da Sul-Americana",
      "Seu time ficou em terceiro lugar no grupo da Libertadores e foi eliminado, mas garantiu uma vaga nas oitavas de final da Sul-Americana.",
      "O jogador $1 demonstrou um desejo de se aposentar. Talvez não seja a melhor ideia mantê-lo em atividade.",
      "Seu time foi eliminado da Liga dos Campeões, mas garantiu uma vaga em uma das fases da Conference League"
      ,
      "A diretoria concluiu a avalia\u00e7\u00e3o mensal.",
      "Um novo contrato de patroc\u00ednio foi assinado.",
      "Uma meta do contrato de patroc\u00ednio foi cumprida."
   };
}
